spring:
  profiles:
    active: local

app:
  version: 1
  title: Parking Management Api
  description: Parking Management Api built for fun

---

spring:
  profiles: local

mongodb:
  host: localhost
  port: 27017
  database: test

accounts:
  admins:
    emails: admin@admin.com
    passwords: $2a$10$jWi5E.WRHlKlvEllxY6al.ANBS/uylxxkAetIq8P0QFDipgcCUahe

---

spring:
  profiles: container

mongodb:
  host: ${MONGO_SERVICE_HOST}
  port: ${MONGO_SERVICE_PORT}
  database: test

accounts:
  admins:
    emails: ${ADMIN_EMAIL}
    passwords: ${PASSWORD_EMAIL}
