apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: NodePort
  ports:
  - name: default
    port: 80
    targetPort: 8080
    nodePort: 30280
  selector:
    app: pma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      name: pma
      labels:
        app: pma
    spec:
      containers:
        - image: valerioferretti/parking-management-api:1.0.0
          name: pma
